#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# User routes
app.user.create:
    path: /api/users
    controller: App\Controller\User\CreateUserAction
    methods: [POST]

app.user.update:
    path: /api/users/{id}
    controller: App\Controller\User\UpdateUserAction
    methods: [PUT]

app.user.update.all:
    path: /api/users/update-all
    controller: App\Controller\User\UpdateUserScoreAction
    methods: [POST]

app.user.get:
    path: /api/users/{id}
    controller: App\Controller\User\GetUserByIdAction
    methods: [GET]

# Profile routes
app.profile.get:
    path: /api/profile/{id}
    controller: App\Controller\Profile\GetProfileByIdAction
    methods: [GET]

# Employee routes
app.employee.get:
    path: /api/employees
    controller: App\Controller\Employee\GetEmployeeAction
    methods: [GET]

app.employee.create:
    path: /api/employees/transactions
    controller: App\Controller\Employee\CreateEmployeeAction
    methods: [POST]
